FROM bde2020/hadoop-base:2.0.0-hadoop2.7.4-java8

COPY core-site.xml /etc/hadoop/
COPY hdfs-site.xml /etc/hadoop/
COPY mapred-site.xml /etc/hadoop/
COPY yarn-site.xml /etc/hadoop/
COPY hadoop-env.sh /etc/hadoop/
